.TH "TON-PUSH" "1" "2022-09-26" "ton" "ton - Transfer Over Network"
.
.SH "NAME"
ton push \- Send a file over the network to someone running \fBton pull\fR
.
.SH "SYNOPSIS"
.nf
\fBton push\fR [\fIoptions\fR] \fIpath\fR ...
.fi
.
.SH "DESCRIPTION"
.PP
Listen for the presence of a corresponding \fBton pull\fR process on the
network, then send the named files or directories to it.
.PP
By default, \fBton push\fR will generate a random passphrase and print it to
standard error. The user running \fBton pull\fR is expected to type in that
passphrase when prompted. Both endpoints must be on the same network
(specifically, the pushing side must be able to receive private-address-range
UDP multicast packets from the pulling side and the pushing side must be able
to make a TCP connection to the pulling side), and they must use the same
passphrase.
.PP
The supplied pathnames may consist of files or directories. All these files and
directories will be copied over the network and written to \fBton pull\fR's
destination directory. Symlinks, device files and socket files are ignored.
File permission bits are preserved where possible, but some systems do not
support all the Unix file permissions.
.
.SH "OPTIONS"
.IP "\fB\-4\fR, \fB\-\-ipv4\fR"
Use IPv4 only, not IPv6.
.IP "\fB\-6\fR, \fB\-\-ipv6\fR"
Use IPv6 only, not IPv4.
.IP "\fB\-\-discover\-port\fR \fIport\fR"
Specify the discovery port number. This is the UDP port number on which we
expect to receive announcement packets from \fBton pull\fR, which must be
using the same port number. The default is 51205.
.IP "\fB\-h\fR, \fB\-\-help\fR"
Show help and exit.
.IP "\fB\-\-hide\-passphrase\fR"
If we are prompting for a passphrase (see \fB\-\-prompt\-passphrase\fR), don't
echo the passphrase as it is typed.
.IP "\fB\-\-include\-global\fR"
Listen for announcements on global as well as private IP addresses.
.IP "\fB\-\-multicast-address-ipv4\fR \fIaddress\fR" 
Specify the IPv4 multicast group address on which we expect to receive
announcement packets. The \fBton pull\fR process must use the same address.
The default is 239.199.77.5, which is for use on private networks.
.IP "\fB\-\-multicast-address-ipv6\fR \fIaddress\fR"
Specify the IPv6 multicast group address on which we expect to receive
announcement packets. The \fBton pull\fR process must use the same address.
The default is ff08:5206:dd93:4290:0891:d264:1444:bd21, which is a private
multicast address with organization-local scope.
.IP "\fB\-\-passphrase\fR \fIstring\fR"
Use this specific passphrase rather than generating or prompting for one.
Conventionally a passphrase is multiple words, but it may be any arbitrary
byte string.
.IP "\fB\-\-prompt\-passphrase\fR"
Don't generate a random passphrase, but prompt for one at the terminal.
.IP "\fB\-\-send\-full\-metadata\fR"
Before sending all the files, send a full list of all the files to be
transferred. This gives the receiving side an opportunity to review the list
and cancel the transfer if desired. That functionality isn't yet implemented
in \fBton pull\fR so this option is not enabled by default.
.IP "\fB\-t\fR, \fB\-\-timeout\fR \fIsec\fR"
Time out if no connection is established after \fIsec\fR seconds. The default
is 0, which disables the timeout.
.IP "\fB\-w\fR, \fB\-\-words\fR \fIcount\fR"
Generate a passphrase with \fIcount\fR words, if we're generating a passphrase.
The default is 4.
.IP "\fB\-v\fR, \fB\-\-verbose\fR"
Show extra diagnostic output, including details of announcement packets
received and where we're trying to connect to as a result.
.
.SH "EXAMPLES"
.PP
All these examples assume there's someone on the nework running \fBton pull\fR
with the same passphrase as us.
.IP "Send a single file:"
.nf
$ \fBton push rickroll.mp3\fR
.fi
.IP "Send multiple files:"
.nf
$ \fBton push rickroll.mp3 ./Pictures/cat.jpg\fR
.fi
.IP "Send a directory and everything in it:"
.nf
$ \fBton push ./Pictures/\fR
.fi
.IP "Send a file, not use IPv6, and supply your own passphrase:"
.nf
$ \fBton push -4 --passphrase "hovercraft full of eels" ./cat.jpg\fR
.fi
.SH "SEE ALSO"
\fBton\fR(1), \fBton-pull\fR(1)
